language: node_js
node_js:
  - "4"
  - "5"
  - "6"
before_script:
  - npm install -g coveralls
  - npm install -g szero
script:
  - make ci
notifications:
  irc: "chat.freenode.net#brass-monkey"
after_success:
  - cat ./coverage/lcov.info | coveralls