language: node_js
dist: trusty
node_js:
  - "4"
  - "6"
  - "7"
before_script:
  - npm install -g coveralls
  - npm install -g szero
script:
  - make ci
notifications:
  irc: "chat.freenode.net#brass-monkey"
after_success:
  - npm run coverage
  - cat ./coverage/lcov.info | coveralls